In [15]:
import pennylane as qml
from pennylane import numpy as np

In [16]:
# this part of the code take a string and convert it to the binary representation using ASCII

word = "cab"

def string_to_ascii(input_string):
    ascii_values = [ord(char) for char in input_string]
    return ascii_values

def string_to_binary_ascii(input_string):
    binary_values = [format(ord(char), '08b') for char in input_string]
    return binary_values

print(f'ASCII representation for "{word}" is {string_to_ascii(word)}')

print(f'Binary form using 8bits is {string_to_binary_ascii(word)}')
print()


# ASCII would require too much precision, than lets make it simple
# lets assume a = 1, b = 2 and c = 3 ...

encoding = {'a':1,'b':2,'c':3}

def string_to_binary(input_string):
    binary_values = [format(encoding[char], '03b') for char in input_string]
    return binary_values

print(f'Using simplified encoding with 3 bits : {string_to_binary(word)}')


ASCII representation for "cab" is [99, 97, 98]
Binary form using 8bits is ['01100011', '01100001', '01100010']

Using simplified encoding with 3 bits : ['011', '001', '010']


In [17]:
# Example word with three bits per character
word_char = string_to_binary("cab")  # Example word to encode
print(word_char)

word = ''.join(word_char)
print(word)


['011', '001', '010']
011001010


In [8]:
# Create the quantum circuit
dev = qml.device("default.qubit", wires=len(word))
@qml.qnode(dev)
def circuit(word):
    for i in range(0, len(word), 3):  # Iterate over the word in steps of three bits
        bit_sequence = word[i:i+3]
        # Convert the three-bit sequence to an integer between 0 and 7
        value = int(bit_sequence, 2)
        
        # Use the integer value to determine which gates to apply
        if value == 0:
            continue  # No operation for '000'
        elif value == 1:
            qml.X(i)  # Apply X gate for '001'
        elif value == 2:
            qml.Y(i)  # Apply Y gate for '010'
        elif value == 3:
            qml.Z(i)  # Apply Z gate for '011'
        elif value == 4:
            qml.H(i)  # Apply H gate for '100'
        elif value == 5:
            qml.S(i)  # Apply S gate for '101'
        elif value == 6:
            qml.T(i)  # Apply T gate for '110'
        elif value == 7:
            qml.CZ((i, (i+1)%len(word)))  # Apply CZ gate for '111'
    
    return [qml.probs(wires=i) for i in range(len(word))]


In [9]:
# Execute the circuit to get probabilities
probabilities = circuit(word)

In [10]:
# Decode the probabilities to retrieve the original word
retrieved_word = ''
for i in range(0, len(word), 3):  # Process every three bits
    bit_sequence = word[i:i+3]
    # Convert the three-bit sequence back to its original form
    retrieved_word += chr(int(bit_sequence, 2) + ord('0'))

In [11]:
print(f'Numeric representation of the retrived word : {retrieved_word}')
print()

Numeric representation of the retrived word : 312



In [12]:
word

'011001010'

In [14]:
probabilities

[tensor([1., 0.], requires_grad=True),
 tensor([1., 0.], requires_grad=True),
 tensor([1., 0.], requires_grad=True),
 tensor([0., 1.], requires_grad=True),
 tensor([1., 0.], requires_grad=True),
 tensor([1., 0.], requires_grad=True),
 tensor([0., 1.], requires_grad=True),
 tensor([1., 0.], requires_grad=True),
 tensor([1., 0.], requires_grad=True)]