In [130]:
import pennylane as qml
from pennylane import numpy as np

## Issue : 

1. **Encoding the Word**:
   - The word is converted to a binary representation using ASCII values. Each character is represented by 8 bits.
   - The total number of bits used is 8 bits per character, which is 24 bits for the word "cab".

2. **Creating the Quantum Circuit**:
   - The binary representation of the word is processed in steps of 3 bits.
   - Each step of 3 bits corresponds to a unique gate operation (X, Y, Z, Hadamard, S, T, or CZ).
   - The total number of bits used is 3 bits per character, which is 9 bits for the word "cab".

3. **Executing the Circuit**:
   - The quantum circuit is executed to generate probabilities for each qubit.
   - The total number of bits used is the same as the number of qubits, which is 9 bits for the word "cab".

4. **Decoding the Word**:
   - The probabilities are processed in steps of 3 bits to determine the most likely outcome for each qubit.
   - Each step of 3 bits corresponds to a character in the original word.
   - The total number of bits used is 3 bits per character, which is 9 bits for the word "cab".

5. **Decoding the Word (Function)**:
   - The function processes the probabilities in steps of 3 bits to determine the most likely outcome for each qubit.
   - Each step of 3 bits corresponds to a character in the original word.
   - The total number of bits used is 3 bits per character, which is 9 bits for the word "cab".

In summary, the number of bits used at each step is:

- Encoding: 24 bits
- Creating the Quantum Circuit: 9 bits
- Executing the Circuit: 9 bits
- Decoding the Word: 9 bits
- Decoding the Word (Function): 9 bits

Issue faced is bit conversion - Let's check


In [131]:
def encode(input_string):
    encoding = ['000', '001', '010', '011', '100', '101', '110', '111', '000', '001', '010', '011', '100', '101', '110', '111', '000', '001', '010', '011', '100', '101', '110', '111']
    output_string = ''
    for char in input_string.lower():
        if char >= 'a' and char <= 'z':
            output_string += encoding[ord(char) - ord('a')]
        else:
            output_string += '000'
    return output_string

# Example usage:
input_string = "cab"
encoded_string = encode(input_string)

In [132]:
print(encoded_string)

010000001


In [146]:
def encode(input_string) : 
    output_string = ''
    for char in input_string.lower() : 
        output_string += encoding.get(char, '')

    return output_string


Example word with three bits per character 

In [134]:
word = "cab" # Example word to encode

Convert the word into a binary representation


In [135]:
binary_word = encode(word)

Create the quantum circuit

* What the function does : 
    * Initialization : 
        * The function starts by initializing a quantum device with the number of wires equal to the length of binary string.
        * The quantum circuit is defined using the '@qml.qnode(dev)' decorator.

    * Processing the Binary String : 
        * The binary string is processed in steps of three bits.
        * For each step of three bits, the function extracts the three-bits sequence and converts it to an integer between o and 7.

    * Gate Operations : 
        * Based on the integer value, the function applies different quantum gates to the coreesponding qubits. 
        * Here's what each gate does : 
            * PauliX(i) : Applies the Pauli-X gate to the qubit at index 'i'. This gate rotates to state of the qubit by 90 degrees.
            * PauliY(i) : Applies the Pauli-Y gate to the qubit at index 'i'. This gate rotates the state of the qubit by 90 degrees.
            * Hadamard(i) : Applies the HAdamard gate to the qubit at index 'i'. This gate creates a superposition of the states |0> abd |1> (Qubit states).
            * S(i) : Applies the S gate to the qubit at index 'i'. This gate rotates the state of the qubit by 90 degrees.
            * T(i) : Applies the T gate to the qubit at index 'i'. This gate rotates the state of the qubit by 90 degrees.
            * CZ((i, (i+1)%len(binary_word))) : Applies the controlled-Z gate to the qubits at indices 'i' and '(i+1)%len(binary_word)'. Ths gate flips the state of the second qubit if the first qubit is in the state |1>.

    * Measuring the Qubits : 
        * After applying the gates, the function measures the probabilities of each qubit in the computational basis.

In [136]:
dev = qml.device("default.qubit", wires = len(binary_word))

@qml.qnode(dev)
def circuit(binary_word):
    for i in range(0, len(binary_word), 3) : 
        bit_sequence = binary_word[i:i+3]

        # Convert the three-bit sequence to an integer between 0 and 7
        value = int(bit_sequence, 2)

    # Use the integer value to determine which gates to apply
    if value == 0: 
        qml.PauliX(i)   # Apply X gate for '000'

    elif value == 1:
        qml.PauliX(i)   # Apply X gate for '001'

    elif value == 2:
            qml.PauliY(i)  # Apply Y gate for '010'
        
    elif value == 3:
        qml.PauliZ(i)  # Apply Z gate for '011'
        
    elif value == 4:
        qml.Hadamard(i)  # Apply Hadamard gate for '100'
    
    elif value == 5:
        qml.S(i)  # Apply S gate for '101'
    
    elif value == 6:
        qml.T(i)  # Apply T gate for '110'
    
    elif value == 7:
        qml.CZ((i, (i+1)%len(binary_qord)))     # Apply CZ gate for '111'

    return [qml.probs(wires = i) for i in range(len(binary_word))]

Execute the circuit to get probabilies


In [153]:
probabilities = circuit(binary_word)


In [154]:
probabilities

[tensor([1., 0.], requires_grad=True),
 tensor([1., 0.], requires_grad=True),
 tensor([1., 0.], requires_grad=True),
 tensor([1., 0.], requires_grad=True),
 tensor([1., 0.], requires_grad=True),
 tensor([1., 0.], requires_grad=True),
 tensor([0., 1.], requires_grad=True),
 tensor([1., 0.], requires_grad=True),
 tensor([1., 0.], requires_grad=True)]

Decode the probabilities to retrieve the original word 

In [139]:
retrieved_word = ''

for i in range(0, len(binary_word), 3):  # Process every three bits
    bit_sequence = binary_word[i:i+3]

    # Convert the three-bit sequence back to its original form
    retrieved_word += chr(int(bit_sequence, 2))

print(f"Retrieved Word : {retrieved_word}")

Retrieved Word : 


* The probabilities are processed in steps of 3 bits, corresponding to the 3-bit encoding used for each character.

* For each group of 3 qubits:
    * The probabilities for each qubit are extracted and stored in a list (qubit_probabilities).
    * A new bit sequence is constructed by checking the most likely outcome for each qubit:
        * If the probability of the qubit being in state |1> is greater than 0.5, a '1' is appended to the bit sequence.
        * Otherwise, a '0' is appended to the bit sequence.
    * The constructed bit sequence is converted back to a character using chr(int(bit_sequence, 2)).
    * The decoded character is appended to the retrieved_word string.

In [140]:
print(f"Bit Sequence : {bit_sequence}, Probabilities : {qubit_probabilities}, Determined Bits : {bit_sequence}")

Bit Sequence : 010, Probabilities : [tensor(1., requires_grad=True), tensor(0., requires_grad=True), tensor(0., requires_grad=True)], Determined Bits : 010


Add a new function to decode the word from the ouput probabilities 


In [141]:
def decode_word(probabilities) : 
    decoded_word = ''
    for i in range(0, len(probabilities), 3):
        qubit_probabilities = [p[1] for p in probabilities[i:i+3]]  # Calculate the probabilities for each qubit

        bit_sequence = ''

        for qubit_probability in qubit_probabilities:
            if qubit_probability > 0.5:
                bit_sequence += '1'
            else:
                bit_sequence += '0'

        decoded_word += chr(int(bit_sequence, 2))

    return decoded_word

In [142]:
probabilities

[tensor([1., 0.], requires_grad=True),
 tensor([1., 0.], requires_grad=True),
 tensor([1., 0.], requires_grad=True),
 tensor([1., 0.], requires_grad=True),
 tensor([1., 0.], requires_grad=True),
 tensor([1., 0.], requires_grad=True),
 tensor([0., 1.], requires_grad=True),
 tensor([1., 0.], requires_grad=True),
 tensor([1., 0.], requires_grad=True)]

Retrieve the original word from the output probabilities 

In [143]:
retrieved_word_probabilities = decode_word(probabilities)

In [144]:
print(f"Encoded word : {word}")

Encoded word : cab


In [145]:
print(f"Retrieved Word : {retrieved_word_probabilities}")

Retrieved Word : 
